# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2.3
      with:
        publish-dir: './dist'  # Replace with your build output directory
        production-branch: 'main'
        netlify-auth-token: nfp_V42uPwD27PeeBTrtDWi1uLLZzcBH1gAHae4a 
        netlify-site-id: 1de416a5-81bb-4a5f-ade7-4790bfd43a4f
